### ISSUE TITLE
Issue installing from pip

### ISSUE THREAD

**Issue by att14** [msanders/cider#24]
Using OSX 10.10.1 I am getting https://gist.github.com/anonymous/ab0b99539a2f799352c2

```
pip 1.5.6 from /Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg (python 2.7)
```

If I run with `pip3` it installs properly, but `cider restore` fails with

```
Traceback (most recent call last):
  File "/usr/local/bin/cider", line 9, in <module>
    load_entry_point('cider==1.1.5', 'console_scripts', 'cider')()
  File "/usr/local/lib/python3.4/site-packages/cider/_cli.py", line 251, in main
    cli.main(standalone_mode=False)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/cider/_cli.py", line 113, in restore
    cider.restore(ignore_errors=ignore_errors)
  File "/usr/local/lib/python3.4/site-packages/cider/core.py", line 202, in restore
    self._assert_requirements()
  File "/usr/local/lib/python3.4/site-packages/cider/core.py", line 176, in _assert_requirements
    if not self._has_xcode_tools():
  File "/usr/local/lib/python3.4/site-packages/cider/core.py", line 163, in _has_xcode_tools
    os.path.join(developer_dir, "usr", "bin", "git")
  File "/usr/local/Cellar/python3/3.4.1_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/posixpath.py", line 92, in join
    "components.") from None
TypeError: Can't mix strings and bytes in path components.
```

```
pip 1.5.6 from /usr/local/lib/python3.4/site-packages (python 3.4)
```

Sorry if I am missing something obvious. If you need more information let me know.

**Comment by msanders** [comment]
Thanks for reporting this. Are you able to install from master?

`pip install https://github.com/msanders/cider/archive/master.zip`

**Comment by att14** [comment]
No I am still getting the same error with Python 2. It looks like Python 3 depends on `yaml`.

```
Traceback (most recent call last):
  File "/usr/local/bin/cider", line 9, in <module>
    load_entry_point('cider==1.1.5', 'console_scripts', 'cider')()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources.py", line 2302, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources.py", line 2029, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/site-packages/cider/__init__.py", line 1, in <module>
    from .core import Cider
  File "/usr/local/lib/python3.4/site-packages/cider/core.py", line 10, in <module>
    from ._sh import (
  File "/usr/local/lib/python3.4/site-packages/cider/_sh.py", line 14, in <module>
    import yaml
ImportError: No module named 'yaml'
```

**Comment by att14** [comment]
I assume Python 2 does as well, but I can't get that far.

**Comment by msanders** [comment]
Any luck now?

**Comment by att14** [comment]
Works for me. Thanks for the quick turnaround!
